config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show,:edit,:update] #users/:idのようなURLになる
  resources :items do
    resources :item_imgs, only: [:show]
    resources :reviews, only: [:new,:create,:show]
    collection do
      get 'search'
    end
  end
  root to: "top#index"
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :item_categories
  has_many :items,through: :item_categories
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :item_brand
  belongs_to :item_category
  has_many :item_imgs
  belongs_to :user
  has_many :reviews
  has_many :users, through: :reviews
  has_many :item_categories
  has_many :categories, through: :item_categories

end

app/models/item_brand.rb
class ItemBrand < ActiveRecord::Base
  has_many :items
end

app/models/item_category.rb
class ItemCategory < ActiveRecord::Base
  belongs_to :item
  belongs_to :category
end

app/models/item_img.rb
class ItemImg < ActiveRecord::Base
  belongs_to :item
  has_many :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :item
  belongs_to :user
  belongs_to :item_img
end

app/models/scraping.rb
class Scraping
  def self.get_links
    links = []
    current_url = "http://www.cosme.net/item/item_id/802/products"
    while true do
      agent = Mechanize.new
      page = agent.get(current_url)
      elements = page.search('.item-head .item a')
      elements.each do |ele|
        links << ele[:href]
      end
      break unless page.at('.cmn-paging .next a')
      # あとで消す
      if current_url == "http://www.cosme.net/item/item_id/802/products/page/19"
        break
      end
      next_url = page.at('.cmn-paging .next a')[:href]
      current_url = next_url
    end
    links.each do |link|
      get_item(link)
    end
  end


  def self.get_item(link)
    agent = Mechanize.new
    page = agent.get(link)
    # brandを作る
    brand = page.at('.brd-name a').inner_text
    item_brand = ItemBrand.where(brand: brand).first_or_create
    #itemを作る
    value = page.search('.info-rating .info-desc')[2].inner_text
    name = page.at('.pdct-name a').inner_text
    item = item_brand.items.where(name: name).first_or_create
    # binding.pry
    item.update(value: value)
    #categoryとitem_categoryを作る
    category_elements = page.search('.item-category a:last')
    category_elements.each do |ele|
      category_text = ele.inner_text
      category = Category.where(category: category_text).first_or_create
      category.item_categories.where(item_id: item.id).first_or_create
    end
    #item_imgを作る(colorとitem_img)
    color_elements = page.search(".color-txt")
    img_elements = page.search(".color-pic .pic img")
    color_img_elements = color_elements.zip(img_elements)
    color_img_elements.each do |color_ele, img_ele|
      color_text = color_ele.inner_text
      item_img = ItemImg.create(item_id: item.id, color: color_text)
      # item_img.update(color: color_text)
      img_url = img_ele[:src]
      item_img.update(img_url: img_url)
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_attached_file :icon, styles: { medium: "300x300>", thumb: "100x100>"}
  validates_attachment_content_type :icon, content_type: ["image/jpg","image/jpeg","image/png"]
  has_many :reviews
  has_many :items,through: :reviews
  def full_profile?
    user_name? && icon?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user! #ログインしてないときにログイン画面にリダイレクトさせる
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/item_imgs_controller.rb
class ItemImgsController < ApplicationController
  def show
    @item_imgs = Item_img.all
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def search
    @search_items = Item.where('name LIKE(?)',"%#{params[:item_keyword]}%").limit(50)
    @search_brands = ItemBrand.where('brand LIKE(?)',"%#{params[:brand_keyword]}%").limit(50)
    @items = Item.all
    @categories = Category.all
    @cat = Category.where(category: params[:category_input])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def show
    @review = Review.find(params[:id])
  end

  def new
    @items = Item.all
    @item_imgs = ItemImg.all
    @review = Review.new
    @item = Item.find(params[:item_id])
  end

  def create
    Review.create(review_params)
    redirect_to user_path(current_user)
  end

private
  def review_params
    params.require(:review).permit(:how_often, :review, :item_img_id).merge(user_id: current_user.id, item_id: params[:item_id])
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @imgs  = ItemImg.find([1, 100, 500, 400])
    @users = User.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])#URLを踏んだ時にユーザーのidがparamsで送られてくる、それを利用する
    @reviews = Review.where(user_id: params[:id])
    @other_users = User.limit(20)
  end

  def edit
  end

  def delite
    redirect_to root_path
  end

  def update
    current_user.update(update_params)
  end

  private
  def update_params
    params.require(:user).permit(:user_name, :icon, :profile)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/item_imgs_helper.rb
module ItemImgsHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/common/_login_logo.html.erb
<div class='sign_up_logo'>
  <small></small>
</div>

app/views/item_imgs/show.html.erb
<% @item_imgs.each do |item_img| %>
 <%= item_img.color %>
<% end %>

app/views/items/search.html.erb
<div class="container">
  <p>あなたのコスメを検索！</p>
  <div class="item_search">
    <%= form_tag('/items/search', method: :get) do %>
      <input name="item_keyword" placeholder="アイテム名で検索" type="string" value=""><button type="submit"><span class="glyphicon glyphicon-search" aria-hidden="true" type="submit"></span></button></input>
      <div class="after-search">
        <% unless params[:item_keyword].blank? %>
          <p>検索結果</p>
          <%= image_tag('cosmekko_logo.jpeg', :class => "logo") %>
          <% @search_items.each do |item| %>
            <ul>
            <li style="border: solid 1px; padding:10px; margin:10px;" class="col-xs-12"><%= item.item_brand.brand %> / #<%= item.name %></li>
            <li class="col-xs-12"><%= item.value %></li>
            <% item.item_imgs.each do |img| %>
            <li class="col-xs-4 left">
              <%= link_to image_tag(img.img_url) ,new_item_review_path(item, item_img_id: img.id),controller: "items", action:"search" %>
            </li>
            <% end %>
            </ul>
         <% end %>
        <% end %>
      </div>
  <% end %>
  </div>

  <div class="brand_search">
    <%= form_tag('/items/search', method: :get) do %>
      <input name="brand_keyword" placeholder="ブランド名で検索" type="string" value=""><button class="btn-search" type="submit"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button></input>
      <!-- アイテムの検索結果 -->
    <div class="after-search">
      <% unless params[:brand_keyword].blank? %>
        <p>検索結果</p>
        <%= image_tag('cosmekko_logo.jpeg', :class => "logo") %>
        <% @search_brands.each do |brand| %>
          <% brand.items.each do |item| %>
          <ul>
          <li style="border: solid 1px; padding:10px; margin:10px;" class="col-xs-12">#<%= brand.brand %> / <%= item.name %></li>
          <li class="col-xs-12"><%= item.value %></li>
      <!-- ブランドの検索結果 -->
          <% item.item_imgs.each do |img| %>
            <li class="col-xs-4 left">
              <%= link_to image_tag(img.img_url) ,new_item_review_path(item, item_img_id: img.id),controller: "items", action:"search" %>
            </li>
          <% end %>
        <% end %>
        </ul>
      <% end %>
    <% end %>
    </div>
    <% end %>
    <form accept-charset="utf-8" action="/" class="js-search-submit" method="get"></form>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer id="contact" class="footer col-xs-12">
  <div class="contents">
      <ul class="footer-share">
        <li><i class="btn-instagram"></i></a></li>
      </ul>
      <p>© 2016 All rights reserved. All Rights Reserved<br>
        made<i class="fa fa-heart pulse"></i> by <a href="http://www.designstub.com/">NATSUONATSU</a></p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="top-contents">
  <a href=<%= root_path %>><span class="header">cosmekko</span></a>
  </div>
<!--     <ul class="dropdown">
      <li><a class="dropdown-toggle" data-toggle="dropdown"><b class="caret"></b></a>
      <ul class="dropdown-menu"> -->
  <div class="menu">
    <% unless signed_in? %>
      <span><%= link_to 'ログイン', new_user_session_path %></span>
    <% end %>
    <% if signed_in? %>
      <span><%= link_to 'マイページ', user_path(current_user) %></span>
      <span><%= link_to 'ログアウト', '/users/sign_out',method: :delete %></span>
    <% end %>
  </div>
<!--     </ul>
    </li>
    </ul> -->
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='ja'>
  <head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=Edge,chrome=1'>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>oriapp</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>

  <body>
  <%= render 'layouts/header' %>
  <div class="contents">
  <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
  </body>
</html>

app/views/reviews/new.html.erb
<div class="review-items">
  <ul>
    <span style="border: solid 1px; padding:10px;"><%= @items.find(params[:item_id]).name %></span>
    <li class="move-little-down"><%= image_tag @item_imgs.find(params[:item_img_id]).img_url %></li>
    <li><%= @item_imgs.find(params[:item_img_id]).color %></li>
  </ul>
  </div>
<div class="contents review">
<p>\\コスメ登録//</p>
<ul>
  <%= form_for [@item, @review] do |f| %>
    <li>ヘビロテ度</li>
    <li><%= f.number_field :how_often, placeholder: '使用頻度',value: 1, max: 5, min: 1 %></li>
    <li>どんなふうに使ってる？</li>
    <li><%= f.text_area :review, placeholder: '毎日のメイクにかかせないヘビロテアイテム。細かいパールが肌を綺麗に見せてくれる！頬骨の一番高いところにオンしています。' , size: "40", maxlength:"200" %></li>
    <li><%= f.hidden_field :item_img_id,value: params[:item_img_id] %></li>
    <li class="move-little-down"><%= button_tag type="submit" do %>
    In your Pouch!!
    <% end %></li>
  <% end %>
  </ul>
</div>

app/views/reviews/show.html.erb
<div class="contents">
  <ul>
  <li><%= @review.item.item_brand.brand %></li>
  <li><%= @review.item.name %></li>
  <li><%= image_tag(@review.item_img.img_url) %></li>
  <li><%= @review.item_img.color %></li>
  <br>
  <%= image_tag('cosmekko_logo.jpeg', :class => "logo") %>
  <p>comments</p>
  <li><%= @review.how_often %></li>
  <p><%= @review.review %></p>
  </ul>
</div>
<div class="contents">
  <%= image_tag('cosmekko_logo.jpeg', :class => "logo") %>
  <p>このアイテムがポーチに入っているユーザー</p>
    <% @review.item.reviews.each do |review| %>
      <div class="col-xs-4">
        <ul><li><%= review.user.user_name %></li>
        <li><%= link_to image_tag(review.user.icon, :class => "other_user_icon"),  user_path(review.user.id) %></li></ul>
      </div>
    <% end %>
</div>

app/views/top/index.html.erb
<div class="top contents">
  <!-- 名前とアイコンをまず登録してもらう -->
  <% if signed_in? %>
    <% unless current_user.full_profile? %>
      <div class="header_top panel panel-default col-lg-12 no-profile" style="padding:100px;">
        <p>ご登録ありがとうございます！まずはプロフィール設定をしましょう！</p>
        <%= link_to "プロフィール登録", edit_user_path(current_user), { class: "btn btn-lg" } %>
      </div>
    <% end %>
  <% end %>
  <div class="top-img col-xs-12">
    <p class="text">What's in your pouch?</p>
  </div>

  <div class="top-text col-xs-12">
    <h4>毎日のメイクをコーディネイト</h4>
        <% @imgs.each do |img| %>
      <%= image_tag(img.img_url) %>
    <% end %>
    <p class="search_link">3stepであなたのコスメを最大限活用しましょう</P>
    <br>
    <p>1 あなたのコスメを検索</p>
    <br>
    <p>2 コメントを書いてポーチへイン！</p>
    <br>
    <p>3 同じコスメを持っている<br>ユーザーとつながれます</p>
    <br>
  </div>
  <div class="top-search col-xs-12">
    <p>▼早速検索！</p>
    <% if signed_in? %>
    <span class="search_link"><%= link_to "コスメを検索","/items/search" %></span>
    <% else %>
    <span class="search_link"><%= link_to "コスメを検索", new_user_session_path %></span>
    <% end %>
    <br><br><p>すべての最新コスメがカテゴリ、ブランドから検索できます</p>
  </div>
  <p>おすすめユーザーのポーチを見てみる</p>
  <%= image_tag('cosmekko_logo.jpeg', :class => "logo") %>
  <% @users.each do |user| %>
     <ul>
      <div class="col-xs-4">
        <li><%= user.user_name %></li>
        <li><%= link_to image_tag(user.icon, :class => "other_user_icon"),  user_path(user.id) %></li>
      </div>
      </ul>
    <% end %>
  </div>
</div>
<!-- JS FILES --> 
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script> 
<script src="js/bootstrap.min.js"></script> 
<script src="js/jquery.flexslider-min.js"></script> 
<script src="js/retina.min.js"></script> 
<script src="js/modernizr.js"></script> 
<script src="js/main.js"></script>

app/views/users/edit.html.erb
<div class="contents">
  <%= form_for current_user do |f| %>
    <div class="form-group">
      <h4>ユーザー情報変更</h4>
      <ul>
      <li>ユーザーネーム</li>
      <li><%= f.text_field :user_name, placeholder: "ユーザーネーム", class: "form-control" %></li>
      <li>プロフィール※200文字以内</li>
      <li><%= f.text_field :profile, placeholder: "プロフィール", class: "form-control", :size=>"200×50", :maxlength=>"200" %></li>
      <li>プロフィール画像</li>
      <li><%= f.file_field :icon, class: "form-control floating-label", placeholder: "画像アップロード" %></li>
      </ul>
    </div>
    <div class="form-group">
      <span><%= f.submit "更新", class: "btn" %></span>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="contents">
  <!-- アイコン未設定時の対応 -->
  <% if signed_in? %>
    <% unless current_user.full_profile? %>
      <div class="header_top col-xs-12 no-profile">
        <p>ご登録ありがとうございます！まずはプロフィール設定をしましょう！</p>
        <%= link_to "プロフィール登録", edit_user_path(current_user), { class: "btn btn-lg" } %>
      </div>
    <% else %>
    <div class="userpage">
      <div class="userpage-icon col-xs-6">
        <ul>
        <li><%= image_tag(@user.icon(:medium), :class => "mypage_icon") %></li></ul>
      </div>
      <div class="userpage-profile col-xs-6">
      <ul>
        <li><%= @user.user_name %></li>
        <li><%= @user.profile %></li>
        <li><%= link_to '編集', edit_user_path(current_user) %></li>
      </ul>
      </div>
    </div>
    <% end %>
  <% else %>
  <!-- サインアップしてない人が見れるようにする -->
  <li><%= image_tag(@user.icon(:medium), :class => "mypage_icon") %></li>
  <% end %>
  <!-- コンテンツ -->
  <div class="col-xs-12 user-search">
    <article>
    <% if current_user == @user %>
      <span class="search_link">
        <%= link_to "コスメを登録","/items/search" %>
      </span>
    <% end %>
    </article>
  </div>
</div>
<div class="contents">
  <article>
    <section id="portfolio">
        <div class="row">
          <% @reviews.each do |review| %>
          <div class="col-xs-4 portfolio-item">
          <ul>
            <!-- <li><%= review.item.name %></li> -->
            <!-- <li><%= review.item_img.color %></li> -->
            <li><%= link_to image_tag(review.item_img.img_url), item_review_path(review.item_id,review.id) %></li>
          </ul>
          </div>
        <% end %>
      </div>
    </section>
  </article>
  <div class="contents move-little-down">
    <p>ほかのユーザーのポーチをみてみる</p>
    <%= image_tag('cosmekko_logo.jpeg', :class => "logo") %>
    <% @other_users.each do |user| %>
      <ul>
      <div class="col-xs-4">
        <li><%= user.user_name %></li>
        <li><%= link_to image_tag(user.icon, :class => "other_user_icon"),  user_path(user.id) %></li>
      </div>
      </ul>
    <% end %>
  </div>
</div>

app/views/users/update.html.erb
<div class="form-group">
  <div class="row form">
    <div class="col-lg-12">
      <h3>プロフィールの編集が完了しました。</h3>
      <%= link_to "マイページ", user_path %>
    </div>
  </div>
</div>